# Use root/example as user/password credentials
version: '3.1'

 
services:
  db:
    image: mysql:8.3.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes: 
      - "./back-end/db:/var/lib/mysql"
    ports:
      - 127.0.0.1:${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 127.0.0.1:8080:80

  web:
    image: nginx
    restart: always
    volumes:
      - ./front-end:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx  
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:8081:80"


