# Use root/example as user/password credentials
version: '3.1'

 
services:
  app:
    image: web-login
    restart: always
    ports:
      - 127.0.0.1:8082:2996
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}

  chat:
    image: web-chat
    restart: always
    ports:
      - 127.0.0.1:8083:8083

  db:
    image: mysql:8.3.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes: 
      - "./back-end/db:/var/lib/mysql"
    ports:
      - 127.0.0.1:${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
    ports:
      - 127.0.0.1:8080:80

  web:
    image: web-page
    restart: always
    ports:
      - "127.0.0.1:8081:80"


