name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate time stamp
      run: | 
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
    
    - name: print image_tag    
      run: echo "${{env.IMAGE_TAG}}"

    - name: Build the back-end image
      run: docker build . --file ./back-end/Dockerfile --tag polaris0618/web-login:$IMAGE_TAG

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER  }}
        password: ${{ secrets.DOCKER_TOKEN  }}

    - name: Push to Docker Hub
      run: docker push polaris0618/web-login:$IMAGE_TAG

