name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Echo secrets
      run: echo ${{ secrets.DOCKER_USER  }}
    - name: Generate time stamp
      run: | 
        export IMAGE_TAG=$(date +%s)
        echo $IMAGE_TAG
    - name: Build the back-end image
      run: docker build . --file ./back-end/Dockerfile --tag polaris0618/web-login:${{IMAGE_TAG}}
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER  }}
        password: ${{ secrets.DOCKER_TOKEN  }}
    - name: Run docker images
      run: docker images
      
    - name: Push to Docker Hub
      run: docker push polaris0618/web-login:${{IMAGE_TAG}}

